### PR TITLE
Major update for webservices at CLST, Radboud University, Nijmegen (auto-harvested)

### PR DESCRIPTION
**Pull request by proycon**
This PR updates the tool registry for our CLAM-based webservices. There are some major changes:

* We just finished an internal migration, our webservices are now at https://webservices.cls.ru.nl instead of https://webservices-lst.science.ru.nl , although the old links should all redirect nicely (HTTP 301), I can imagine this may be confusing to the handler on the switchboard side and possibly lead to errors in the current production environment.
* Some webservices were removed and some new ones were added.
* The CLAM webservice metadata has been harvested automatically and converted to the registry json format, this was done by a script which invokes by [clam2switchboard](https://github.com/proycon/clam2switchboard) tool. The actual script is included in this PR in the ``contrib/harvest`` directory  (I imagine it could hold various kinds of user contributed harvesting scripts). This means you can update the tool metadata even without my intervention, by just running the script.
   * Many of our webservices support multiple inputs, this now results in duplication and a new entry for each. I'll be happy to adapt my harvester/converter once #28 is resolved (I see you've been working on it in #60). 

An extra round of testing is still required to ensure that all these all work properly. I remember you guys have nice automated systems for that right?

### CODE REVIEW

**Comment by emanueldima** [comment]
@proycon json validation fails, do you have access to travis? (https://travis-ci.org/github/clarin-eric/switchboard-tool-registry/builds/731614143). Most of the errors are missing logos (must be a string). You can also run the validation yourself, see the command in the travis file: https://github.com/clarin-eric/switchboard-tool-registry/blob/master/.travis.yml

**Comment by proycon** [comment]
Thanks, I see it now yes! I'll prepare a fix

**Comment by proycon** [comment]
The validation now passes successfully.

**Comment by emanueldima** [comment]
@andmor- @dietervu  I guess we should merge this to production?

**Comment by dietervu** [comment]
Before merging this to production, I tried to check https://beta-switchboard.clarin.eu/ and https://switchboard.clarin-dev.eu/switchboard-test/ to test-drive these changes. But it seems they are not available. Is this correct or did I overlook something?

**Comment by emanueldima** [comment]
@proycon Could you add a logo image for these tools? Otherwise they will be displayed with a missing logo: https://beta-switchboard.clarin.eu/tools

**Comment by proycon** [comment]
Good point, I'll send a new PR with some logo images soon.

**Comment by proycon** [comment]
It seems some of the logos that are already present are not being shown? Like frog.jpg , might this be a bug? Or do they necessarily have to pngs now?

**Comment by emanueldima** [comment]
Most image files are supported, an entry of `"logo": "x"` in the tool json file will be translated to a `https://beta-switchboard.clarin.eu/api/logos/x`. The frog is there, you just have to set "frog.jpg" as the logo: https://beta-switchboard.clarin.eu/api/logos/frog.jpg

**Comment by proycon** [comment]
That's what I thought yes, but for example the frog logo doesn't show on https://beta-switchboard.clarin.eu/tools even though the API call works.

**Comment by emanueldima** [comment]
I don't see any tools that have this logo in the json file, am I missing something?

**Comment by proycon** [comment]
Hmm, indeed, I guess I was looking in another git branch. I see now that they are missing from this PR.

**Comment by dietervu** [comment]
FTR: I have been and am test-driving the CLAM services and once the last glitches are resolved (I'm communicating with proycon about this) this PR can be merged. I'll give an update in this thread.

**Comment by andmor-** [comment]
To merge this in `production` the `contrib/harvest` has to be removed. We have to discuss this but I think that this repository is not the place for tool specific scripts (or any type of code in general)

**Comment by andmor-** [comment]
I am removing it to be be able to merge the metadata part to `production`.
If needed we can later create a new repository for code for specific tools.

**Comment by emanueldima** [comment]
@proycon We decided it would be better to store all **contrib** code in a separate repository, something like `github.com/clarin-eric/switchboard-tools-contrib`. We should not get foreign code in this repository as it is replicated into the switchboard instances. But we'd like to have the contrib code together in a single place. However we (e.g. clarin-eric) cannot be responsible for contrib code and should not have to maintain it. Do you think that's a good idea, would you add your contrib to this repository?

**Comment by proycon** [comment]
@emanueldima That sounds like a good solution yes! If you create the repo then I'll gladly push my harvest script there.

**Comment by andmor-** [comment]
[New repository created](https://github.com/clarin-eric/switchboard-tool-registry-contrib)

**Pull request merged**
