### PR TITLE
Update Clarin-PL tools to use new services page

### PR DESCRIPTION
**Pull request by daawidziu**
Deleted tools definitions that are no longer maintained. Updated other tools to use new page instead of old one.

### CODE REVIEW

**Comment by andmor-** [comment]
If you need check here how to run the validators locally: https://github.com/clarin-eric/switchboard-tool-registry/blob/master/.github/workflows/main.yml#L18

**Comment by daawidziu** [comment]
Validation errors should be fixed now

**Comment by andmor-** [comment]
Would you like this to be propagated to production?

**Comment by daawidziu** [comment]
I need to fix a few things first. As written in the README, I should be able to test my tools at https://beta-switchboard.clarin.eu/, but I can't see them there. Could you check on that?

**Comment by andmor-** [comment]
Fixed. The problem was that your PR inserted a duplicated name here:
https://github.com/clarin-eric/switchboard-tool-registry/pull/170/files#diff-a42083f1e8ea68dbdba773239a7f1cb5b5d6ffe7c92e452841d497d060d6b4d5R7

I fixed this here:
https://github.com/clarin-eric/switchboard-tool-registry/commit/e0c816b3aa35a93c9634a89a8bbc04883558d7ac

Now now the tools show up as expected. But please verify that the name I changed is as you would like it to be.

**Pull request merged**
