### PR TITLE
new tool to master branch (1)

### PR DESCRIPTION
**Pull request by procesaur**

### CODE REVIEW

**Comment by procesaur** [comment]
I think our JSON is ok now,

**Comment by procesaur** [comment]
The tool is up on the beta switchboard now, however clicking it produces a js error.

**Comment by andmor-** [comment]
Fixed. You have to provide a `mediatypes` array for each `input` object, even if marked as `optional`. I added this and it now works. Please see [this commit](https://github.com/clarin-eric/switchboard-tool-registry/commit/03dcb119d4ede241f8d729bd2d20bd433f29b679) and, if needed, change the mediatypes to the ones that the tool input's actually support

**Comment by procesaur** [comment]
Understandable. Those are actually checkboxes for different features, but I guess we are to make a separate JSON for each one then, which will total in four I believe.

**Pull request merged**
