### PR TITLE
Added new task categories

### PR DESCRIPTION
**Pull request by proycon**
I propose several new task categories (see the diff of the json schema), all motivated by real services we offer.

I also corrected some of the current metadata for the Nijmegen-based services.

### CODE REVIEW

**Comment by andmor-** [comment]
It all looks good to me but the new task categories should be a little discussed/reviewed by the others. 
If you separate this in 2 PRs, I can immediately merge the changes for the Nijmegen-based services.

**Comment by emanueldima** [comment]
It would be nice to have an external complete taxonomy to base our tasks on. Does anyone know about anything related?

**Comment by andmor-** [comment]
Not at all, but we can try to do some googling

**Comment by proycon** [comment]
(I split off #35 as requested)

I agree that basing on an external complete taxonomy would be nice, if such a thing exists. I also wonder if something external can ever be 'complete' enough so there should be some kind of extensibility.

**Comment by andmor-** [comment]
I agree that unless we find a magical taxonomy, we will definitely need some custom entries, so some extension/modification mechanism will be needed. Still I think that if there is such an accepted taxonomy out there, we should start from it.

**Comment by emanueldima** [comment]
I propose to accept this PR and systematize the tasks later.

**Pull request merged**
